### ISSUE TITLE
Mortality analysis - how to limit sample

### ISSUE THREAD

**Issue by anderaa** [anderaa/BioEcon_Knobel#8]
Are we ok with limiting the sample to dogs with entry after 1/1/2012? We still have older dogs in the population because some dogs enter the population as adults. But I'm not sure it is ok.

**Comment by jcnavin** [comment]
I was thinking about this last night regarding average abundance and max abundance, at first I thought we might have to keep it that way because I'm calculating abundance on a per-day basis, however I think that we can get away with just using the minimum entry date of dogs that we have sufficient information on (i.e. a birthdate, an entry date, and an exit date)

**Comment by anderaa** [comment]
We will use all dogs but only retain rows that represent days during 2012-2015.
